### ISSUE TITLE
How many memory this micropython use? only 4MB or bigger?

### ISSUE THREAD

**Issue by yingshaoxo** [boochow/micropython-raspberrypi#40]
Because some people say micropython only use 4MB of memory.

But pi zero has 64MB+ memory.

If your project cant allow us to use those memory, that will be a sad thing.

**Comment by baseplate-admin** [comment]
> But pi zero has 64MB+ memory.

It is 512 MB to be exact.

> If your project cant allow us to use those memory, that will be a sad thing.

I can say that python will allocate as much as you need ( and maybe even more using swap ). I dont think people will run large libraries that consume huge amount of ram on micropython
